export const provinces = [
  { label: "Aklan", value: "Aklan" },
  { label: "Antique", value: "Antique" },
  { label: "Capiz", value: "Capiz" },
  { label: "Guimaras", value: "Guimaras" },
  { label: "Iloilo", value: "Iloilo" },
  { label: "Negros Occidental", value: "Negros Occidental" },
];

export const tbiProvinces = [
  "All",
  "Aklan",
  "Antique",
  "Capiz",
  "Guimaras",
  "Iloilo",
  "Negros Occidental",
];

// Municipalities
export const aklanMunicipalities = [
  { label: "Altavas", value: "Altavas" },
  { label: "Balete", value: "Balete" },
  { label: "Banga", value: "Banga" },
  { label: "Batan", value: "Batan" },
  { label: "Buruanga", value: "Buruanga" },
  { label: "Ibajay", value: "Ibajay" },
  { label: "Kalibo (Capital)", value: "Kalibo (Capital)" },
  { label: "Lezo", value: "Lezo" },
  { label: "Libacao", value: "Libacao" },
  { label: "Madalag", value: "Madalag" },
  { label: "Makato", value: "Makato" },
  { label: "Malay", value: "Malay" },
  { label: "Malinao", value: "Malinao" },
  { label: "Nabas", value: "Nabas" },
  { label: "New Washington", value: "New Washington" },
  { label: "Numancia", value: "Numancia" },
  { label: "Tangalan", value: "Tangalan" },
];
export const antiqueMunicipalities = [
  "Anini-y",
  "Barbaza",
  "Belison",
  "Bugasong",
  "Caluya",
  "Culasi",
  "Hamtic",
  "Laua-an",
  "Libertad",
  "Pandan",
  "Patnongon",
  "San Jose (Capital)",
  "San Remigio",
  "Sebaste",
  "Sibalom",
  "Tibiao",
  "Tobias Fornier (Dao)",
  "Valderrama",
];
export const capizMunicipalities = [
  "City of Roxas (Capital)",
  "Cuartero",
  "Dao",
  "Dumalag",
  "Dumarao",
  "Ivisan",
  "Jamindan",
  "Ma-ayon",
  "Mambusao",
  "Panay",
  "Panitan",
  "Pilar",
  "Pontevedra",
  "President Roxas",
  "Sapi-an",
  "Sigma",
  "Tapaz",
];
export const guimarasMunicipalities = [
  "Buenavista",
  "Jordan (Capital)",
  "Nueva Valencia",
  "San Lorenzo",
  "Sibunag",
];
export const iloiloMunicipalities = [
  "Ajuy",
  "Alimodian",
  "Anilao",
  "Badiangan",
  "Balasan",
  "Banate",
  "Barotac Nuevo",
  "Barotac Viejo",
  "Batad",
  "Bingawan",
  "Cabatuan",
  "Calinog",
  "Carles",
  "City of Iloilo (Capital)",
  "City of Passi",
  "Concepcion",
  "Dingle",
  "Dueñas",
  "Dumangas",
  "Estancia",
  "Guimbal",
  "Igbaras",
  "Janiuay",
  "Lambunao",
  "Leganes",
  "Lemery",
  "Leon",
  "Maasin",
  "Miag-ao",
  "Mina",
  "New Lucena",
  "Oton",
  "Pavia",
  "Pototan",
  "San Dionisio",
  "San Enrique",
  "San Joaquin",
  "San Miguel",
  "San Rafael",
  "Santa Barbara",
  "Sara",
  "Tigbauan",
  "Tubungan",
  "Zarraga",
];
export const negrosOccidentalMunicipalities = [
  "Binalbagan",
  "Calatrava",
  "Candoni",
  "Cauayan",
  "City of Bacolod (Capital)",
  "City of Bago",
  "City of Cadiz",
  "City of Escalante",
  "City of Himamaylan",
  "City of Kabankalan",
  "City of La Carlota",
  "City of Sagay",
  "City of San Carlos",
  "City of Silay",
  "City of Sipalay",
  "City of Talisay",
  "City of Victorias",
  "Enrique B. Magalona (Saravia)",
  "Hinigaran",
  "Hinoba-an (Asia)",
  "Ilog",
  "Isabela",
  "La Castellana",
  "Manapla",
  "Moises Padilla (Magallon)",
  "Murcia",
  "Pontevedra",
  "Pulupandan",
  "Salvador Benedicto",
  "San Enrique",
  "Toboso",
  "Valladolid",
  "Cauayan",
];
